import { access, mkdir, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { loadProjectConfig, ProjectConfigSchema } from "../config/index.js";
import { runCommand, runQuickCommand } from "./run.js";
import type { ProjectConfig, ProviderName } from "../config/index.js";

type PolicyMode = "auto" | "safe-only" | "manual";
type StopMode = "drain" | "hard";
type PermissionScope = "delegated-safe" | "delegated-full" | "manual";
type AuthMode = "api" | "subscription";

interface InitCommandOptions {
  config?: string;
  cwd?: string;
  version?: string;
}

interface ModelRef {
  provider: ProviderName;
  model: string;
}

const BANDMASTER_BANNER = [
  "  ____                  _ __  __           _            ",
  " |  _ \\                | |  \\/  |         | |           ",
  " | |_) | __ _ _ __   __| | \\  / | __ _ ___| |_ ___ _ __ ",
  " |  _ < / _` | '_ \\ / _` | |\\/| |/ _` / __| __/ _ \\ '__|",
  " | |_) | (_| | | | | (_| | |  | | (_| \\__ \\ ||  __/ |   ",
  " |____/ \\__,_|_| |_|\\__,_|_|  |_|\\__,_|___/\\__\\___|_|   "
].join("\n");

const PROVIDERS: ProviderName[] = ["codex", "claude", "gemini", "ollama"];
const DEFAULT_MODEL_BY_PROVIDER: Record<ProviderName, string> = {
  codex: "gpt-5.3-codex",
  claude: "claude-opus-4-1",
  gemini: "gemini-3-pro-preview",
  ollama: "llama3.1:8b"
};

const DEFAULT_API_ENV_BY_PROVIDER: Record<ProviderName, string | undefined> = {
  codex: "OPENAI_API_KEY",
  claude: "ANTHROPIC_API_KEY",
  gemini: "GEMINI_API_KEY",
  ollama: undefined
};

const SUBSCRIPTION_AUTH_COMMAND: Record<Exclude<ProviderName, "ollama">, string> = {
  codex: "codex login",
  claude: "claude setup-token",
  gemini: "gemini auth login"
};

const LEGACY_MODEL_REWRITES: Partial<Record<ProviderName, Record<string, string>>> = {
  codex: {
    "gpt-5-codex": "gpt-5.3-codex",
    "gpt-5.2-codex": "gpt-5.3-codex"
  },
  claude: {
    "claude-sonnet-4-5": "claude-opus-4-1",
    "opus-4.6": "claude-opus-4-1"
  },
  gemini: {
    "gemini-2.0-flash": "gemini-3-pro-preview",
    "gemini-3.1-pro": "gemini-3-pro-preview"
  }
};

const LEGACY_SUBSCRIPTION_COMMAND_REWRITES: Record<string, string> = {
  "codex --login": "codex login"
};

function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function normalizeEntryDocs(value: string): string[] {
  return value
    .split(",")
    .map((doc) => doc.trim())
    .filter((doc) => doc.length > 0);
}

function normalizeModel(provider: ProviderName, model: string): string {
  const rewrites = LEGACY_MODEL_REWRITES[provider];
  if (!rewrites) {
    return model;
  }
  return rewrites[model] ?? model;
}

function normalizeDraftConfig(draft: ProjectConfig): ProjectConfig {
  draft.worker.primary.model = normalizeModel(
    draft.worker.primary.provider,
    draft.worker.primary.model
  );
  draft.worker.fallback = draft.worker.fallback.map((ref) => ({
    ...ref,
    model: normalizeModel(ref.provider, ref.model)
  }));

  draft.pm.primary.model = normalizeModel(draft.pm.primary.provider, draft.pm.primary.model);
  draft.pm.fallback = draft.pm.fallback.map((ref) => ({
    ...ref,
    model: normalizeModel(ref.provider, ref.model)
  }));

  for (const provider of Object.keys(draft.providers)) {
    const auth = draft.providers[provider]?.auth;
    if (!auth || auth.mode !== "subscription" || !auth.subscriptionCommand) {
      continue;
    }
    auth.subscriptionCommand =
      LEGACY_SUBSCRIPTION_COMMAND_REWRITES[auth.subscriptionCommand] ??
      auth.subscriptionCommand;
  }

  return draft;
}

function toProjectToml(config: ProjectConfig): string {
  const lines: string[] = [
    "# Bandmaster project config generated by `bandmaster init`.",
    "",
    "[project]",
    `name = ${tomlString(config.project.name)}`,
    `objective = ${tomlString(config.project.objective)}`,
    `workspace = ${tomlString(config.project.workspace)}`,
    `entryDocs = [${config.project.entryDocs.map(tomlString).join(", ")}]`,
    "",
    "[worker.primary]",
    `provider = ${tomlString(config.worker.primary.provider)}`,
    `model = ${tomlString(config.worker.primary.model)}`,
    ""
  ];

  for (const fallback of config.worker.fallback) {
    lines.push(
      "[[worker.fallback]]",
      `provider = ${tomlString(fallback.provider)}`,
      `model = ${tomlString(fallback.model)}`,
      ""
    );
  }

  lines.push(
    "[pm.primary]",
    `provider = ${tomlString(config.pm.primary.provider)}`,
    `model = ${tomlString(config.pm.primary.model)}`,
    ""
  );

  for (const fallback of config.pm.fallback) {
    lines.push(
      "[[pm.fallback]]",
      `provider = ${tomlString(fallback.provider)}`,
      `model = ${tomlString(fallback.model)}`,
      ""
    );
  }

  lines.push(
    "[pm.userProxy]",
    `enabled = ${config.pm.userProxy.enabled}`,
    `permissionScope = ${tomlString(config.pm.userProxy.permissionScope)}`,
    `guidanceStyle = ${tomlString(config.pm.userProxy.guidanceStyle)}`,
    "",
    "[policy]",
    `mode = ${tomlString(config.policy.mode)}`,
    "",
    "[checkpoint]",
    `intervalMinutes = ${config.checkpoint.intervalMinutes}`,
    "",
    "[dialogue]",
    `enableWorkerPmLoop = ${config.dialogue.enableWorkerPmLoop}`,
    `interveneOnPermission = ${config.dialogue.interveneOnPermission}`,
    `interveneOnDirectionRequest = ${config.dialogue.interveneOnDirectionRequest}`,
    `interveneOnStall = ${config.dialogue.interveneOnStall}`,
    `stallMinutes = ${config.dialogue.stallMinutes}`,
    "",
    "[budget]",
    `maxMinutes = ${config.budget.maxMinutes}`,
    `maxTokens = ${config.budget.maxTokens}`,
    `maxTurns = ${config.budget.maxTurns}`,
    `stopMode = ${tomlString(config.budget.stopMode)}`,
    "",
    "[budget.cycle]",
    `maxTokens = ${config.budget.cycle.maxTokens}`,
    `maxTurns = ${config.budget.cycle.maxTurns}`,
    ""
  );

  const providerNames = Object.keys(config.providers).sort((a, b) =>
    a.localeCompare(b)
  );
  for (const provider of providerNames) {
    const auth = config.providers[provider]?.auth;
    if (!auth) {
      continue;
    }
    lines.push(`[providers.${provider}.auth]`, `mode = ${tomlString(auth.mode)}`);
    if (auth.mode === "api" && auth.apiKeyEnv) {
      lines.push(`apiKeyEnv = ${tomlString(auth.apiKeyEnv)}`);
    }
    if (auth.mode === "subscription" && auth.subscriptionCommand) {
      lines.push(`subscriptionCommand = ${tomlString(auth.subscriptionCommand)}`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function createDefaultConfig(cwd: string): ProjectConfig {
  return ProjectConfigSchema.parse({
    project: {
      name: path.basename(cwd) || "bandmaster-project",
      objective: "Build the software described in README.md and supporting docs.",
      workspace: ".",
      entryDocs: ["README.md"]
    },
    worker: {
      primary: {
        provider: "codex",
        model: DEFAULT_MODEL_BY_PROVIDER.codex
      },
      fallback: [
        {
          provider: "claude",
          model: DEFAULT_MODEL_BY_PROVIDER.claude
        }
      ]
    },
    pm: {
      primary: {
        provider: "claude",
        model: DEFAULT_MODEL_BY_PROVIDER.claude
      },
      fallback: [
        {
          provider: "gemini",
          model: DEFAULT_MODEL_BY_PROVIDER.gemini
        }
      ],
      userProxy: {
        enabled: true,
        permissionScope: "delegated-safe",
        guidanceStyle: "direct-and-push-forward"
      }
    },
    policy: {
      mode: "safe-only"
    },
    checkpoint: {
      intervalMinutes: 20
    },
    dialogue: {
      enableWorkerPmLoop: true,
      interveneOnPermission: true,
      interveneOnDirectionRequest: true,
      interveneOnStall: true,
      stallMinutes: 8
    },
    budget: {
      maxMinutes: 480,
      maxTokens: 1500000,
      maxTurns: 400,
      stopMode: "drain",
      cycle: {
        maxTokens: 60000,
        maxTurns: 24
      }
    },
    providers: {
      codex: {
        auth: {
          mode: "subscription",
          subscriptionCommand: "codex login"
        }
      },
      claude: {
        auth: {
          mode: "subscription",
          subscriptionCommand: "claude setup-token"
        }
      },
      gemini: {
        auth: {
          mode: "subscription",
          subscriptionCommand: "gemini auth login"
        }
      }
    }
  });
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await access(targetPath);
    return true;
  } catch {
    return false;
  }
}

function validatePositiveInteger(rawValue: string): string | undefined {
  if (!/^\d+$/.test(rawValue)) {
    return "Enter a positive integer.";
  }
  const parsed = Number.parseInt(rawValue, 10);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    return "Enter a positive integer.";
  }
  return undefined;
}

function getFallbackDefault(primary: ProviderName, preferred: ProviderName): ProviderName {
  if (primary !== preferred) {
    return preferred;
  }
  const alternate = PROVIDERS.find((provider) => provider !== primary);
  return alternate ?? primary;
}

function uniqueProviders(providers: ProviderName[]): ProviderName[] {
  const set = new Set<ProviderName>(providers);
  return Array.from(set);
}

function formatModel(ref: ModelRef): string {
  return `${ref.provider}/${ref.model}`;
}

function formatConnection(config: ProjectConfig, provider: ProviderName): string {
  const auth = config.providers[provider]?.auth;
  if (!auth) {
    return "local";
  }
  if (auth.mode === "api") {
    return `API (${auth.apiKeyEnv ?? "missing-env"})`;
  }
  return `Subscription (${auth.subscriptionCommand ?? "missing-command"})`;
}

function formatRoleSummary(
  primary: ModelRef,
  fallback: ModelRef[],
  config: ProjectConfig
): string {
  const primaryText = `${formatModel(primary)} | ${formatConnection(config, primary.provider)}`;
  if (fallback.length === 0) {
    return primaryText;
  }
  const fallbackText = fallback
    .map((item) => `${formatModel(item)} | ${formatConnection(config, item.provider)}`)
    .join(", ");
  return `${primaryText}; fallback: ${fallbackText}`;
}

export async function initCommand(options: InitCommandOptions): Promise<void> {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error("Interactive init requires a TTY terminal.");
  }

  const cwd = options.cwd ?? process.cwd();
  const configPath = path.resolve(cwd, options.config ?? ".bandmaster/project.toml");
  const rl = createInterface({ input, output });
  const configuredProvidersInSession = new Set<ProviderName>();

  const askText = async (
    question: string,
    defaultValue: string,
    validate?: (value: string) => string | undefined
  ): Promise<string> => {
    while (true) {
      const answer = (await rl.question(`${question} [${defaultValue}]: `)).trim();
      const value = answer.length > 0 ? answer : defaultValue;
      const message = validate ? validate(value) : undefined;
      if (!message) {
        return value;
      }
      console.log(message);
    }
  };

  const askChoice = async <T extends string>(
    question: string,
    optionsList: readonly T[],
    defaultValue: T
  ): Promise<T> => {
    while (true) {
      console.log(question);
      optionsList.forEach((option, index) => {
        const marker = option === defaultValue ? " (default)" : "";
        console.log(`  ${index + 1}. ${option}${marker}`);
      });
      const answer = (
        await rl.question(`Choose 1-${optionsList.length} [${defaultValue}]: `)
      ).trim();
      if (answer.length === 0) {
        return defaultValue;
      }
      const parsed = Number.parseInt(answer, 10);
      if (Number.isInteger(parsed) && parsed >= 1 && parsed <= optionsList.length) {
        const selected = optionsList[parsed - 1];
        if (selected !== undefined) {
          return selected;
        }
      }
      console.log("Enter a valid option number.");
    }
  };

  const askBoolean = async (question: string, defaultValue: boolean): Promise<boolean> => {
    const suffix = defaultValue ? "[Y/n]" : "[y/N]";
    while (true) {
      const answer = (await rl.question(`${question} ${suffix}: `)).trim().toLowerCase();
      if (answer.length === 0) {
        return defaultValue;
      }
      if (answer === "y" || answer === "yes") {
        return true;
      }
      if (answer === "n" || answer === "no") {
        return false;
      }
      console.log("Please answer y or n.");
    }
  };

  const askPositiveInt = async (
    question: string,
    defaultValue: number
  ): Promise<number> => {
    const raw = await askText(question, String(defaultValue), validatePositiveInteger);
    return Number.parseInt(raw, 10);
  };

  const askMenuChoice = async (min: number, max: number): Promise<number> => {
    while (true) {
      const answer = (await rl.question(`Choose ${min}-${max}: `)).trim();
      const parsed = Number.parseInt(answer, 10);
      if (Number.isInteger(parsed) && parsed >= min && parsed <= max) {
        return parsed;
      }
      console.log("Enter a valid option number.");
    }
  };

  const runExternalCommand = async (command: string): Promise<number> =>
    new Promise((resolve) => {
      const child = spawn(command, {
        stdio: "inherit",
        shell: true
      });
      child.on("error", () => resolve(1));
      child.on("exit", (code) => resolve(code ?? 1));
    });

  const getCommandBinary = (command: string): string => {
    const [binary] = command.trim().split(/\s+/);
    return binary ?? "";
  };

  const isBinaryAvailable = async (binary: string): Promise<boolean> => {
    if (!binary) {
      return false;
    }
    return new Promise((resolve) => {
      const child = spawn("sh", ["-lc", `command -v ${binary} >/dev/null 2>&1`], {
        stdio: "ignore"
      });
      child.on("error", () => resolve(false));
      child.on("exit", (code) => resolve(code === 0));
    });
  };

  const configureProviderConnection = async (
    draft: ProjectConfig,
    provider: ProviderName
  ): Promise<void> => {
    if (configuredProvidersInSession.has(provider)) {
      const existingAuth = draft.providers[provider]?.auth;
      if (provider === "ollama") {
        console.log("ollama connection already set for this session. Reusing it.");
      } else if (existingAuth) {
        console.log(
          `${provider} connection already configured in this session (${existingAuth.mode}). Reusing it.`
        );
      } else {
        console.log(`${provider} connection already configured in this session. Reusing it.`);
      }
      return;
    }

    if (provider === "ollama") {
      delete draft.providers[provider];
      console.log(`${provider} uses local runtime. No API/subscription setup required.`);
      configuredProvidersInSession.add(provider);
      return;
    }

    const currentAuth = draft.providers[provider]?.auth;
    const defaultModeLabel = "Subscription";
    const modeLabel = await askChoice(
      `Choose ${provider} connection mode:`,
      ["API", "Subscription"] as const,
      defaultModeLabel
    );
    const mode: AuthMode = modeLabel === "API" ? "api" : "subscription";

    if (mode === "api") {
      const apiKeyEnv = await askText(
        `${provider} API key env var`,
        currentAuth?.mode === "api"
          ? (currentAuth.apiKeyEnv ?? DEFAULT_API_ENV_BY_PROVIDER[provider] ?? "API_KEY")
          : (DEFAULT_API_ENV_BY_PROVIDER[provider] ?? "API_KEY"),
        (value) => (value.length > 0 ? undefined : "Env var name is required.")
      );
      draft.providers[provider] = {
        auth: {
          mode: "api",
          apiKeyEnv
        }
      };
      configuredProvidersInSession.add(provider);
      return;
    }

    const selectedCommand = SUBSCRIPTION_AUTH_COMMAND[provider];
    const binary = getCommandBinary(selectedCommand);
    if (await isBinaryAvailable(binary)) {
      console.log(`Starting ${provider} subscription authentication: ${selectedCommand}`);
      rl.pause();
      const exitCode = await runExternalCommand(selectedCommand);
      rl.resume();
      if (exitCode === 0) {
        console.log("Authentication command finished successfully.");
      } else {
        console.log(
          `Authentication command exited with code ${exitCode}. You can rerun it manually: ${selectedCommand}`
        );
      }
    } else {
      console.log(
        `Could not find "${binary}" on PATH. Install the provider CLI and run: ${selectedCommand}`
      );
    }

    draft.providers[provider] = {
      auth: {
        mode: "subscription",
        subscriptionCommand: selectedCommand
      }
    };
    configuredProvidersInSession.add(provider);
  };

  const configureWorker = async (draft: ProjectConfig): Promise<void> => {
    console.log("\nConfigure worker LLM");
    const primaryProvider = await askChoice(
      "Select worker provider:",
      PROVIDERS,
      draft.worker.primary.provider
    );
    const primaryModel = await askText(
      "Worker model",
      draft.worker.primary.provider === primaryProvider
        ? draft.worker.primary.model
        : DEFAULT_MODEL_BY_PROVIDER[primaryProvider],
      (value) => (value.length > 0 ? undefined : "Worker model is required.")
    );

    const hasFallback = draft.worker.fallback.length > 0;
    const useFallback = await askBoolean("Configure worker fallback?", hasFallback);
    const fallback: ModelRef[] = [];
    if (useFallback) {
      const currentFallback = draft.worker.fallback[0];
      const fallbackProvider = await askChoice(
        "Select worker fallback provider:",
        PROVIDERS,
        currentFallback?.provider ??
          getFallbackDefault(primaryProvider, "claude")
      );
      const fallbackModel = await askText(
        "Worker fallback model",
        currentFallback?.provider === fallbackProvider
          ? currentFallback.model
          : DEFAULT_MODEL_BY_PROVIDER[fallbackProvider],
        (value) => (value.length > 0 ? undefined : "Fallback model is required.")
      );
      fallback.push({
        provider: fallbackProvider,
        model: fallbackModel
      });
    }

    draft.worker.primary = {
      provider: primaryProvider,
      model: primaryModel
    };
    draft.worker.fallback = fallback;

    for (const provider of uniqueProviders([
      primaryProvider,
      ...fallback.map((item) => item.provider)
    ])) {
      await configureProviderConnection(draft, provider);
    }
  };

  const configureManager = async (draft: ProjectConfig): Promise<void> => {
    console.log("\nConfigure manager LLM");
    const primaryProvider = await askChoice(
      "Select manager provider:",
      PROVIDERS,
      draft.pm.primary.provider
    );
    const primaryModel = await askText(
      "Manager model",
      draft.pm.primary.provider === primaryProvider
        ? draft.pm.primary.model
        : DEFAULT_MODEL_BY_PROVIDER[primaryProvider],
      (value) => (value.length > 0 ? undefined : "Manager model is required.")
    );

    const hasFallback = draft.pm.fallback.length > 0;
    const useFallback = await askBoolean("Configure manager fallback?", hasFallback);
    const fallback: ModelRef[] = [];
    if (useFallback) {
      const currentFallback = draft.pm.fallback[0];
      const fallbackProvider = await askChoice(
        "Select manager fallback provider:",
        PROVIDERS,
        currentFallback?.provider ??
          getFallbackDefault(primaryProvider, "gemini")
      );
      const fallbackModel = await askText(
        "Manager fallback model",
        currentFallback?.provider === fallbackProvider
          ? currentFallback.model
          : DEFAULT_MODEL_BY_PROVIDER[fallbackProvider],
        (value) => (value.length > 0 ? undefined : "Fallback model is required.")
      );
      fallback.push({
        provider: fallbackProvider,
        model: fallbackModel
      });
    }

    const userProxyEnabled = await askBoolean(
      "Enable manager as user proxy?",
      draft.pm.userProxy.enabled
    );
    const permissionScope = userProxyEnabled
      ? await askChoice(
          "User-proxy permission scope:",
          ["delegated-safe", "delegated-full", "manual"] as const,
          draft.pm.userProxy.permissionScope as PermissionScope
        )
      : "manual";
    const guidanceStyle = await askText(
      "Manager guidance style",
      draft.pm.userProxy.guidanceStyle,
      (value) => (value.length > 0 ? undefined : "Guidance style is required.")
    );

    draft.pm.primary = {
      provider: primaryProvider,
      model: primaryModel
    };
    draft.pm.fallback = fallback;
    draft.pm.userProxy = {
      enabled: userProxyEnabled,
      permissionScope,
      guidanceStyle
    };

    for (const provider of uniqueProviders([
      primaryProvider,
      ...fallback.map((item) => item.provider)
    ])) {
      await configureProviderConnection(draft, provider);
    }
  };

  const configureSettings = async (draft: ProjectConfig): Promise<void> => {
    console.log("\nSettings");
    draft.policy.mode = (await askChoice(
      "Permission policy mode:",
      ["safe-only", "auto", "manual"] as const,
      draft.policy.mode as PolicyMode
    )) as PolicyMode;
    draft.checkpoint.intervalMinutes = await askPositiveInt(
      "Checkpoint interval (minutes)",
      draft.checkpoint.intervalMinutes
    );
    draft.dialogue.interveneOnStall = await askBoolean(
      "Allow manager intervention on stalls?",
      draft.dialogue.interveneOnStall
    );
    if (draft.dialogue.interveneOnStall) {
      draft.dialogue.stallMinutes = await askPositiveInt(
        "Stall threshold (minutes)",
        draft.dialogue.stallMinutes
      );
    }
    draft.budget.maxMinutes = await askPositiveInt(
      "Session max minutes",
      draft.budget.maxMinutes
    );
    draft.budget.maxTokens = await askPositiveInt(
      "Session max tokens",
      draft.budget.maxTokens
    );
    draft.budget.maxTurns = await askPositiveInt(
      "Session max turns",
      draft.budget.maxTurns
    );
    draft.budget.cycle.maxTokens = await askPositiveInt(
      "Cycle max tokens",
      draft.budget.cycle.maxTokens
    );
    draft.budget.cycle.maxTurns = await askPositiveInt(
      "Cycle max turns",
      draft.budget.cycle.maxTurns
    );
    draft.budget.stopMode = (await askChoice(
      "Stop mode at budget end:",
      ["drain", "hard"] as const,
      draft.budget.stopMode as StopMode
    )) as StopMode;
  };

  const runAiWorkAndSave = async (draft: ProjectConfig): Promise<boolean> => {
    console.log("\nRun AI work");
    draft.project.name = await askText(
      "Project name",
      draft.project.name,
      (value) => (value.length > 0 ? undefined : "Project name is required.")
    );
    draft.project.objective = await askText(
      "Project objective",
      draft.project.objective,
      (value) => (value.length > 0 ? undefined : "Project objective is required.")
    );
    draft.project.workspace = await askText(
      "Workspace path",
      draft.project.workspace,
      (value) => (value.length > 0 ? undefined : "Workspace path is required.")
    );
    draft.project.entryDocs = normalizeEntryDocs(
      await askText(
        "Entry docs (comma-separated)",
        draft.project.entryDocs.join(", "),
        (value) =>
          normalizeEntryDocs(value).length > 0
            ? undefined
            : "At least one entry doc is required."
      )
    );

    const parsed = ProjectConfigSchema.parse(draft);
    const exists = await pathExists(configPath);
    if (exists) {
      const overwrite = await askBoolean(
        `Config already exists at ${configPath}. Overwrite?`,
        false
      );
      if (!overwrite) {
        console.log("Run setup cancelled. Existing config left unchanged.");
        return false;
      }
    }

    await mkdir(path.dirname(configPath), { recursive: true });
    await writeFile(configPath, toProjectToml(parsed), "utf8");

    console.log("\n[System] Wrote project config:");
    console.log(`[System] ${configPath}`);
    console.log("\n[System] Starting run with saved config...\n");
    await runCommand({ config: configPath, cwd });
    return true;
  };

  const runQuick = async (draft: ProjectConfig): Promise<boolean> => {
    console.log("\nQuick Run");
    const prompt = await askText(
      "Prompt to Worker LLM",
      draft.project.objective,
      (value) => (value.length > 0 ? undefined : "Prompt is required.")
    );
    const durationMode = await askChoice(
      "Quick run budget mode:",
      ["rounds", "hours"] as const,
      "hours"
    );

    const defaultDuration =
      durationMode === "hours"
        ? Math.max(1, Math.floor(draft.budget.maxMinutes / 60))
        : draft.budget.maxTurns;
    const durationValue = await askPositiveInt(
      durationMode === "hours" ? "Run for how many hours" : "Run for how many rounds",
      defaultDuration
    );

    console.log("\n[System] Starting quick run with inline prompt...\n");
    await runQuickCommand({
      config: draft,
      prompt,
      mode: durationMode,
      value: durationValue
    });
    return true;
  };

  try {
    let draft = createDefaultConfig(cwd);
    if (await pathExists(configPath)) {
      try {
        const loaded = await loadProjectConfig({ configPath, cwd });
        draft = normalizeDraftConfig(loaded.config);
      } catch (error) {
        const detail = error instanceof Error ? error.message : String(error);
        console.warn(`Could not load existing config at ${configPath}. Using defaults.`);
        console.warn(detail);
      }
    }

    draft = normalizeDraftConfig(draft);

    console.log(BANDMASTER_BANNER);
    console.log(`\nv${options.version ?? "0.0.0"}`);

    let finished = false;
    while (!finished) {
      console.log("\nMain Menu");
      console.log(
        `1. Configure worker LLM (${formatRoleSummary(draft.worker.primary, draft.worker.fallback, draft)})`
      );
      console.log(
        `2. Configure manager LLM (${formatRoleSummary(draft.pm.primary, draft.pm.fallback, draft)})`
      );
      console.log(
        `3. Settings (policy=${draft.policy.mode}, checkpoint=${draft.checkpoint.intervalMinutes}m, session=${draft.budget.maxMinutes}m, cycle=${draft.budget.cycle.maxTokens}t)`
      );
      console.log("4. Run AI work (project/docs + save + run)");
      console.log("5. Quick Run (inline prompt + rounds/hours)");
      console.log("6. Exit without saving");

      const choice = await askMenuChoice(1, 6);

      if (choice === 1) {
        await configureWorker(draft);
        continue;
      }
      if (choice === 2) {
        await configureManager(draft);
        continue;
      }
      if (choice === 3) {
        await configureSettings(draft);
        continue;
      }
      if (choice === 4) {
        finished = await runAiWorkAndSave(draft);
        continue;
      }
      if (choice === 5) {
        finished = await runQuick(draft);
        continue;
      }

      console.log("Exited without saving.");
      finished = true;
    }
  } finally {
    rl.close();
  }
}
